### ISSUE TITLE
problem while testing using pretrained models

### ISSUE THREAD

**Issue by amrbenattia** [jiahaoLjh/trajectory-pose-3d#2]

**Comment by amrbenattia** [comment]
thanks for great work, 
I tried to run the code : python test.py --exp 0422_122443_F50_k8_dct_det --gpu 0
however that error happened 

Traceback (most recent call last):
  File "./trajectory-pose-3d-master/test.py", line 188, in <module>
    main()
  File "./trajectory-pose-3d-master/test.py", line 68, in main
    assert len(dir_name) == 1, "Invalid exp folder to load: {}".format(config["args"]["exp"])
AssertionError: Invalid exp folder to load: 0422_122443_F50_k8_dct_det

what is the reason please ?

**Comment by jiahaoLjh** [comment]
This assertion error is caused by that there is no experiment folder detected under the "log" folder. You may either download the model of the experiment we released (refer to README) or change the command line argument "--exp" to your own experiment accordingly.

Cheers.
